project:
  type: book

book:
  title: "Ecological theory for the biodiversity crisis"
  author: "Henrique Miguel Pereira"
  date: today
  repo-url: https://github.com/hmlfpereira/theoeco-book
  downloads: [pdf]
  repo-actions: [source]
  chapters:
    - index.qmd
    - part: "Ecology of individuals"
      chapters:
        - ecophysiology.qmd
        - optimalforaging.qmd
        - gametheory.qmd
        - movement.qmd
    - part: "Ecology of populations"
      chapters:
        - demography.qmd
    - part: "Ecology of communities"
      chapters:
        - modellingbiochange.qmd
  appendices:
    - intro_to_R.qmd
    - labs.qmd
  #  - labs_solutions.qmd     currently empty
  #  - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: "images/BookCover.png"
  pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    number-sections: true
    toc-depth: 2
editor: visual
